{% set name = "ipserver" %}
{% set version = "1.0.1" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ipserver-{{ version }}.tar.gz
  sha256: d140c6f4e991f18822d733d36765391fe02b7f59774221082f69613fb49549ab

build:
  number: 0
  noarch: python
  entry_points:
    - ipserver = ipserver.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

    - multipart

test:
  imports:
    - ipserver
  commands:
    - pip check
    - ipserver --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://deer-hunt.github.io/ipserver/
  license: MIT
  license_file: LICENSE.md
  summary: '"IpServer" is a simple server that supports TCP, UDP, SSL, HTTP, and HTTPS protocols for various uses such as testing, debugging, or network investigation. It features also an interactive mode and forwarding capabilities. Additionally, you can customize its behavior using Python.'
  description: |
    [Features]:
    - Simple TCP / UDP server.
    - Support SSL connection. SSL server.
    - HTTP / HTTPS server.
    - IP restriction - Allow / Deny.
    - Interactive sending.
    - TCP Forwarding. Bypassing the data transmission is available.
    - Display received data or sent data in various format(TEXT, BINARY, BASE64, HEX...).
    - HTTP -> FILE: Viewing file and directory and uploading file.
    - HTTP -> FORWARDING: Forwarding HTTP transmission. e.g. HTTP <-> HTTPS
    - HTTP -> APP: Running python application. And running CGI via python.
    - HTTP -> INFO: Show request headers from client.
    - Support HTTP digest authentication.
    - Logging / Debug log.
    - Dump transmission data to file.
    - Configure by JSON file.
    - Customize by Python code. e.g. You can convert transmission data or develop original protocol server.

  dev_url: https://github.com/deer-hunt/ipserver
  doc_url: https://deer-hunt.github.io/ipserver/

extra:
  recipe-maintainers:
    - deer-hunt
